name: "$(TeamProject) for $(Build.DefinitionName) $(_NEXT_PUBLIC_APP_ENV)"

trigger:
  - develop

resources:
- repo: self

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/infrastructure/docker/cms.Dockerfile'
  tag: '$(Build.BuildId)'
  currentDate: $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]

stages:
- stage: BuildPush
  displayName: Build and push stage
  jobs:  
  - job: ManualApproval
    displayName: Waiting for manual approval
    pool:
      name: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 30
      inputs:
        instructions: 'Please approve to start image build and container app update'
  - job: DockerBuild
    displayName: Build Docker image
    dependsOn: ManualApproval
    pool:
      name: $(_PIPELINE_POOL)
    steps:
    - task: Docker@2
      displayName: Build $(_ACR_IMAGE_REPOSITORY)
      inputs:
        command: build
        repository: $(_ACR_IMAGE_REPOSITORY)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(_ACR_CONNECTION)
        tags: |
         latest
         $(currentDate)-$(tag)
    - task: Docker@2
      displayName: Push $(_ACR_IMAGE_REPOSITORY)
      inputs:
        command: push
        repository: $(_ACR_IMAGE_REPOSITORY)
        containerRegistry: $(_ACR_CONNECTION)
        tags: |
         latest
         $(currentDate)-$(tag)
    - task: AzureCLI@2
      displayName: Update container app
      inputs:
        azureSubscription: $(_AZURE_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp update --resource-group "$(_RESOURCE_GROUP)" --name "$(_ACR_IMAGE_REPOSITORY)-app" -i $(_ACR_HOST)/$(_ACR_IMAGE_REPOSITORY):$(currentDate)-$(tag)
